### ISSUE TITLE
Handling connection in client

### ISSUE THREAD

**Issue by MithrilMan** [davidfowl/BedrockFramework#18] opened 2019-12-29 01:59 UTC
I've updated my code in order to follow you re-design, previously I just implemented the server side, but now I'm digging into the client.
My process actually spawns a single server that uses socket connection with custom protocol, and listen to different endpoints read from config (but still a single Server instance that just have multiple listeners). Whenever I ctrl+C or i close the other end of the communciation, server react in a proper way and disconnect/dispose (even if I see some memory problem, everytime I create connections and close them, memory keep increasing, but it may be caused by other stuff I inject in DI that may survive, will look at that)

About client, I haven't a clear view on how to spawn multiple connections and how to manage properly their life cycle (e.g. if I call connection.abort() the connection doesn't die like I was expecting)

My approach currently is to create a single Client object and use it to call `this.client.ConnectAsync` in a task whenever I need to spawn a new connection to an endpoint
https://github.com/MithrilMan/MithrilShards/blob/41316d2e13fd287a352c402f0aa03e73aecac6aa/src/MithrilShards.Network.Bedrock/BedrockForgeConnectivity.cs#L115-L145

in the code above I used even a `.Use(this.SetupClientConnection)` during Client build I'm actually doing nothing there (is it useful in this context? probably not)
as a test, I spawn a connection right there calling my Attemptconnection and I use a custom class to handle the connection lifetime.

As I said, internally in my class I was expecting to be able to call connection.abort to interrupt that connection but it wasn't working, so in order to make it works like I want, I added a CancellationTokenSource property in one of my internal classes (PeerContext) that I can use to trigger the disconnection.

I assigned then the token of such property to ConnectionClosed property of my connection object
`connection.ConnectionClosed = peerContext.ConnectionCancellationTokenSource.Token;`

this link take to the code part that implement this logic
https://github.com/MithrilMan/MithrilShards/blob/41316d2e13fd287a352c402f0aa03e73aecac6aa/src/MithrilShards.Network.Bedrock/MithrilForgeClientConnectionHandler.cs#L71-L109

and as you can see there I pass connection.ConnectionClosed as the cancellation token for `reader.ReadAsync`
`ReadResult<INetworkMessage> result = await reader.ReadAsync(protocol, connection.ConnectionClosed).ConfigureAwait(false);`

TLTR, actually server and client (at least for what I tested: socket custom protocol implementation) have a different level of easy of use and it's not clear which step to take in order to implement the client connection lifetime in a proper way, can you point me(us?) on the right track?

P.S.
wouldn't be appropriate to have ConfigureAwait(false) calls on async calls in your examples?
thanks and sorry for the wall of text

**Comment by davidfowl** [comment] 2019-12-29 03:06
Firstly @MithrilMan thanks for this feedback. I'm hoping to find people that will build on top of the framework to give this kind of feedback. I want to make writing high performance networking code reliable, easy and extensible. Thanks!

> About client, I haven't a clear view on how to spawn multiple connections and how to manage properly their life cycle (e.g. if I call connection.abort() the connection doesn't die like I was expecting)

Unlike the server, the client side is owned by the caller so you're ultimately responsible for calling `DisposeAsync` after everything is done. Calling Abort should work but if it doesn't client side it's likely a bug in the implementation. Currently the socket client side implementation and server implementation are different and I have to fix that (it's the next thing I'm going to work on). It should resolve these issues.

> My approach currently is to create a single Client object and use it to call this.client.ConnectAsync in a task whenever I need to spawn a new connection to an endpoint
https://github.com/MithrilMan/MithrilShards/blob/41316d2e13fd287a352c402f0aa03e73aecac6aa/src/MithrilShards.Network.Bedrock/BedrockForgeConnectivity.cs#L115-L145

That's right, the client is a factory for connections.

> As I said, internally in my class I was expecting to be able to call connection.abort to interrupt that connection but it wasn't working, so I added a CancellationTokenSource property in one of my internal classes (PeerContext) that I can use to trigger the disconnection.

This shouldn't be needed by the server (assuming this is the server side logic).

> TLTR, actually server and client (at least for what I tested: socket custom protocol implementation) have a different level of easy of use and it's not clear which step to take in order to implement the client connection lifetime in a proper way, can you point me(us?) on the right track?

That's generally because the server is accepting many connections and since the model is a callback model (with the connection handler) it's easier to clean up after the call completes. Unlike the client side where that's in your hands. Besides that it should be similar though. 

Do you have any examples? How are your client side APIs being used?

> wouldn't be appropriate to have ConfigureAwait(false) calls on async calls in your examples?
thanks and sorry for the wall of text

Yes, I need to do this as this library is meant to be app model agnostic. I just made a change to cover most of the places https://github.com/davidfowl/BedrockFramework/commit/64d684ba20e801a575ea5e88b123b47f4ca7e5e3.

**Comment by davidfowl** [comment] 2019-12-29 03:14
Just spend some more time looking at your client example. Since you're using a connection handler on the client side, that logic looks good. The only questions are:

- Who is going to await AttemptConnection? 

Here's an example of a client:

 - Create a new connection - https://github.com/davidfowl/Pubbie/blob/a7722c427a312ee7d558ac1a6aa0038d019b4d04/src/Pubbie/PubSubClient.cs#L53-L56
- Disposing - https://github.com/davidfowl/Pubbie/blob/a7722c427a312ee7d558ac1a6aa0038d019b4d04/src/Pubbie/PubSubClient.cs#L222-L244

Shutdown sequence
- Stop the writer so new writes noop
- CancelPendingRead so we can yield the read loop if there's more data currently being awaited
- Then we wait for the read loop to end 
- Dispose the connection after everything is complete.

**Comment by MithrilMan** [comment] 2019-12-29 11:43
Thanks for the feedback and examples!

> Unlike the server, the client side is owned by the caller so you're ultimately responsible for calling DisposeAsync after everything is done. Calling Abort should work but if it doesn't client side it's likely a bug in the implementation.

Ok so it may be a bug, I think you could simulate it using your LengthPrefixed client implementation and try to call connection.Abort, let me see if I can replicate it modifying your example.

> Currently the socket client side implementation and server implementation are different and I have to fix that (it's the next thing I'm going to work on). It should resolve these issues.

Cool that will be really helpful

Let me give you now some context about what I'm doing:
My repository aim at having building blocks to build blockchain solutions, actually I'm trying to replicate bitcoin protocol and have a full node implementation (of course will require lot of time and it's not even close to be finished)

About client/server connection, a full node works having a server component that's listening on one or more endpoint, and a client component that tries to connect to at least other N nodes (N configurable) and it uses some logic to pick an endpoint to try to connect to (basically it have a list of known endpoints that were previously running a node server component)

So we have to deal with a task that keep trying to connect to endpoints using an address book (so we have a task that does this and it's not awaited) and whenever it finds a peer that responds, starts the handshake sequence and then once passed they start exchanging informations.

So
> Who is going to await AttemptConnection?

I'd say no one, once the connection happens no one should await it and should just have a task running it.
I'll have an external component to keep track of active connections and interact with them e.g. dropping the connection triggering the PeerContext ConnectionCancellationTokenSource .Cancel(), let's call this component `ConnectionManager` , no one is awaiting Attemptconnection and ConnectionManager duty is to keep track of active connection and drop them at will.

For example there could be a case when another peer connect to us but we reached the connection limit (not handled at socket level but at protocol level) and we may want to drop the least performant connected node to let the new one stay connected with us, so ConnectionManager will inspect his stats about connected peers and drop the least performant making room for the new connected peer.

> This shouldn't be needed by the server (assuming this is the server side logic).
No I was talking about client logic, I was calling

Based on your considerations, correct me if I'm wrong, it seems I'm doing things right, so maybe one thing that may be improved is to implement an extension for ClientBuilder like
.UseConnectionHandler (or within UseSockets for Server) and be sure that calling connection.Abort close effectively the client connection

**Comment by MithrilMan** [comment] 2019-12-29 12:09
update on Abort "bug": I updated your example to abort a connection if you type `quit` and it correctly abort the connection
https://github.com/davidfowl/BedrockFramework/compare/master...MithrilMan:bug/client-connection-abort-not-working?expand=1

I don't know if your recent changes on ConfigureAwait could have fixed this or if the problem was in my code, will keep investigate, maybe I was cooding too late in the night/morning :)

**Comment by MithrilMan** [comment] 2019-12-29 12:22
"good news" about the bug, I managed to replicate it
https://github.com/davidfowl/BedrockFramework/compare/master...MithrilMan:bug/client-connection-abort?expand=1

![image](https://user-images.githubusercontent.com/5107375/71556872-00eb9700-2a3e-11ea-9656-e5565143d54e.png)

as you can see from the image, connection didn't dropped when I wrote "quit" and called connection.Abort

https://github.com/MithrilMan/BedrockFramework/blob/d5576e0bcba1ea6604ea53c3ffe0f00131abe7d9/samples/ClientApplication/Program.cs#L229-L232
```
if(line == "quit") {
   Console.WriteLine("Oh, so soon? bye bye.");
   connection.Abort();
}
```

So if you were expecting it to close connection, this is a bug.

**Comment by davidfowl** [comment] 2019-12-29 17:36
> I'd say no one, once the connection happens no one should await it and should just have a task running it.
I'll have an external component to keep track of active connections and interact with them e.g. dropping the connection triggering the PeerContext ConnectionCancellationTokenSource .Cancel(), let's call this component ConnectionManager , no one is awaiting Attemptconnection and ConnectionManager duty is to keep track of active connection and drop them at will.

Sounds good. Just think about how you would go about auditing a hang.

> Based on your considerations, correct me if I'm wrong, it seems I'm doing things right, so maybe one thing that may be improved is to implement an extension for ClientBuilder like
.UseConnectionHandler (or within UseSockets for Server) and be sure that calling connection.Abort close effectively the client connection

https://github.com/davidfowl/BedrockFramework/issues/19. Abort will just work like it should and will end the connection and the reading loop (like it does on the server side). Today it's cancelling the  reader so if you want a stop gap solution, on the reading side, try checking for IsCanceled and see if that works.

**Comment by davidfowl** [comment] 2020-01-02 15:38
Closing as dupe of https://github.com/davidfowl/BedrockFramework/issues/19

**Closed by davidfowl** 2020-01-02 15:38 UTC
