### ISSUE TITLE
gracefull close client connection

### ISSUE THREAD

**Issue by JanEggers** [davidfowl/BedrockFramework#8] opened 2019-10-23 19:16 UTC
when I DisposeAsync the client connection I see this in the logs:

Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   at Bedrock.Framework.SocketConnection.DoSend() in C:\Users\Jan\Source\Repos\MQTTnet\BedrockTransports\Bedrock.Framework\Transports\Sockets\SocketConnection.cs:line 215
   at Bedrock.Framework.SocketConnection.ExecuteAsync() in C:\Users\Jan\Source\Repos\MQTTnet\BedrockTransports\Bedrock.Framework\Transports\Sockets\SocketConnection.cs:line 91

Am I supposed to calling something else before disposeasync or is this a bug?

**Comment by davidfowl** [comment] 2019-11-04 05:38
When do you call it?

**Comment by JanEggers** [comment] 2019-11-04 05:50
at the end of my benchmark

https://github.com/JanEggers/MQTTnet/blob/aspnetcore3/Tests/MQTTnet.Benchmarks/MessageProcessingMqttConnectionContextBenchmark.cs

**Comment by davidfowl** [comment] 2019-12-26 02:46
Need to look into this. It shouldn't happen.

**Comment by davidfowl** [comment] 2020-01-02 15:37
Dupe of https://github.com/davidfowl/BedrockFramework/issues/19

**Closed by davidfowl** 2020-01-02 15:37 UTC
